Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
StringLiterals:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/MutableConstant:
  Enabled: false
